jobs:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:duggan/bats'
          packages:
            - bats
            - python-pygments
      before_install:
        - curl -LO https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
        - sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
      dist: bionic
      language: minimal
    - os: osx
      before_install:
        - brew install bats-core
        - brew install pandoc
        - brew install pygments
        - brew install w3m
      osx_image: xcode11.3

script: bats test
